### ISSUE TITLE
Autoprefixer autoupdates

### ISSUE THREAD

**Issue by ai** [autoprefixer/autoprefixer.github.io#1]
You do not update Autoprefixer 4 months. It is very very bad.

What about getting `autoprefixer.js` from [autoprefixer-rails](https://github.com/ai/autoprefixer-rails/blob/master/vendor/autoprefixer.js) as [other tool do it](http://simevidas.jsbin.com/gufoko/quiet)?

**Comment by ymatuhin** [comment]
Done.

**Comment by ai** [comment]
Awesome, Autoprefixer now use your online demo (in `next6` branch)
