### ISSUE TITLE
`font-smooth: never` with webkit

### ISSUE THREAD

**Issue by lextoc** [autoprefixer/autoprefixer.github.io#10]
Isn't `-webkit-font-smoothing: none` the equivalent of `font-smooth: never`? It doesn't get added my autoprefixer.

Excuse me if I'm wrong, just giving heads up.

**Comment by ymatuhin** [comment]
Ping @ai

**Comment by ai** [comment]
@lextoc please create a issue in Autoprefixer repo https://github.com/postcss/autoprefixer

**Comment by lextoc** [comment]
@ai Woops, done!

https://github.com/postcss/autoprefixer/issues/763
