### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by zooks** [autoprefixer/autoprefixer.github.io#14]
Firefox 53.0b8 (64-bit)

**Comment by ymatuhin** [comment]
Thanks, I'll check this in the evening.

**Comment by ymatuhin** [comment]
I have Firefox 52.0.2 (latest) in my macOS and everything looks all right.

**Comment by ymatuhin** [comment]
Any messages in dev tools?

**Comment by zooks** [comment]
Hi, I rechecked today and it works. Yesterday example code and filter didn't load.
