### ISSUE TITLE
Escape tags in output

### ISSUE THREAD

**Issue by ai** [autoprefixer/autoprefixer.github.io#15]
![bompfzy](https://cloud.githubusercontent.com/assets/19343/25058227/48ba0c7a-21cb-11e7-9c1f-339d6a210215.png)

/cc @ymatuhin

**Comment by badggit** [comment]
Have this problem every time I try to use https://autoprefixer.github.io
Lost tons of my favorite comments because I use the similar comments structure.

**Comment by ymatuhin** [comment]
Thanks, I fix it.

**Comment by badggit** [comment]
@ymatuhin, thanks, but looks like you broke it a little bit. If you have something with ">" in your css now it cases error.
Ex: tr > th
![dbf4a72966e105c2863b9571c9ddfc85 1](https://cloud.githubusercontent.com/assets/2575951/25068191/21b7f896-2264-11e7-927a-dab601fe74e6.png)

**Comment by ymatuhin** [comment]
@badggit thank you, fix it again 😊
