### ISSUE TITLE
Setting browsers doesn't work any more

### ISSUE THREAD

**Issue by thybzi** [autoprefixer/autoprefixer.github.io#18]
Setting browsers list in the input below first works no more.
Anything I set there doesn't change result in any way.
No errors in console (Chrome or Firefox).
Please fix it. Thanks.

**Comment by ymatuhin** [comment]
Ok, I'll check it in the evening. Thanks.

**Comment by ymatuhin** [comment]
@ai, can you help me a little? A changed nothing in code, get autoprefixer.js from autoprefixer-rails and pass browser settings as usual.
`autoprefixer.process(text, { browsers: this.settings.browsers })`

**Comment by ai** [comment]
See https://github.com/postcss/postcss/releases/tag/6.0.0

You need `autoprefixer.process(text, { }, { browsers: this.settings.browsers })`

**Comment by ymatuhin** [comment]
Thanks, now it works.
