### ISSUE TITLE
Online home page syntax error

### ISSUE THREAD

**Issue by Pinchanzee** [autoprefixer/autoprefixer.github.io#19]
This page isn't working: https://autoprefixer.github.io/

It reports a syntax error in chrome (version 57, linux mint)
Uncaught SyntaxError: Unexpected token )
code.js:34

Possibly because of the trailing commas?

**Comment by odahcam** [comment]
Just for knowledge: Works fine in Chrome 59.0.3071.115 + Windows 10.

**Comment by ymatuhin** [comment]
I tried to fix this, tell me please if error still appears.

**Comment by Pinchanzee** [comment]
Yup, all fixed :)
