### ISSUE TITLE
justify-content

### ISSUE THREAD

**Issue by karaeren** [autoprefixer/autoprefixer.github.io#20]
What's the "pack" on justify-content?

`justify-content: center;`
translates to
```
-webkit-box-pack: center;
-ms-flex-pack: center;
justify-content: center;
```
however it should translate to
```
-webkit-justify-content: center;
justify-content: center;
```

**Comment by odahcam** [comment]
Maybe this can be helpfull: https://codepen.io/odahcam/pen/NNZavB

**Comment by ymatuhin** [comment]
I suggest you to ask this question in repo https://github.com/postcss/autoprefixer
