### ISSUE TITLE
Error: Cannot find module 'caniuse-lite/data/regions/RU.js'

### ISSUE THREAD

**Issue by SynCap** [autoprefixer/autoprefixer.github.io#28]
Error: Cannot find module 'caniuse-lite/data/regions/RU.js'
with filter like that: `>1% in RU, last 10 version`

**Comment by yepninja** [comment]
Yeap. It's breaking change in major 3rd browserslist release https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md#30
It's need to minimize size of the bundle in browsers.
