### ISSUE TITLE
Freeze on wrong CSS

### ISSUE THREAD

**Issue by krembo** [autoprefixer/autoprefixer.github.io#3]
The service doesn't work when there is a wrong syntax in CSS. 
It just freezes without any notification to a user.
And there is an "Uncaught object" error in autoprefixer.js file in line 19774.

Cheers for a useful tool!

![image](https://cloud.githubusercontent.com/assets/3259644/10334004/087bc8d8-6cf0-11e5-84ec-5d089aaeaaee.png)

![image](https://cloud.githubusercontent.com/assets/3259644/10334014/1eb44bc0-6cf0-11e5-97c6-02e1486d4243.png)

**Comment by ymatuhin** [comment]
@krembo thanks for issue. Fixed now.
