### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by ai** [autoprefixer/autoprefixer.github.io#3]
SIte must support English too.

**Comment by ymatuhin** [comment]
Add english version in 7ca4d99f6460f984a4394203beeef68a963e9090

**Comment by ai** [comment]
@ymatuhin Но когда я захожу с английского браузера на `autoprefixer.github.io`, то всё равно вижу русскую версию.

Наверное, лучше всего сделать как на [easings.net](http://easings.net/). На корне — английская версия. И [автоперенаправление](https://github.com/ai/easings.net/blob/master/scripts/language-redirect.js.erb) по `navigator.userLanguage`.

**Comment by ymatuhin** [comment]
@ai Это потому, что ты раньше заходил и в localstorage запомнилось. Проверил только что с режима инкогнито — перенаправляет. Какой язык пользователь выбирает сохраняется и перенаправляет туда (чтобы русскоязычные пользователи с английской версией браузера не страдал невозможностью перейти на русскую версию).

**Comment by ai** [comment]
@ymatuhin русскоязычных пользователей меньшинство ;-).

**Comment by ymatuhin** [comment]
@ai Сейчас из поисковиков приходят в основном именно они )

**Comment by ai** [comment]
Я собираюсь изменить ссылку на демо на странице Автопрефиксера на твой смывать, потому что он лучше. Там будет много пользователей.

**Comment by ymatuhin** [comment]
@ai Ок, тогда ты прав и имеет смысл поменять местами. Сейчас займусь.

**Comment by ymatuhin** [comment]
@ai Done.

**Comment by ymatuhin** [comment]
Moved to https://github.com/autoprefixer
