### ISSUE TITLE
Please update to Autoprefixer 9.3.1

### ISSUE THREAD

**Issue by Dan503** [autoprefixer/autoprefixer.github.io#35]
I have an article coming out soon about Autoprefixer 9.3.1 and I link to [autoprefixer.github.io](https://autoprefixer.github.io/) in it as the tool I recommend for viewing real time CSS Grid translations. It would be good if the site was using the latest version.

Also, a heads up, Autoprefixer 9.4.0 will be released at the start of December and introduce CSS Grid auto-placement support.

**Comment by Dan503** [comment]
To support auto-placement translations when 9.4.0 is released, the `grid` setting will need to be changed to `"autoplace"` rather then `true`.

**Comment by ymatuhin** [comment]
I've updated autoprefixer to the 9.3.1, please ping me when 9.4 will be ready, thanks a lot 👍
