### ISSUE TITLE
website API?

### ISSUE THREAD

**Issue by TheWebTech** [autoprefixer/autoprefixer.github.io#37]
Would you be interested in creating an API where a site/service could post css code to the autoprefixer site to then have it return the autoprefixed code?

Use case scenario - I run a chrome extension for developers on the HubSpot platform. HubSpot has an online code editor, it does not prefix for you. I would be interested in integrating into the extension the ability to select text, right click and then click "autoprefix" if you were to have an api for this.

The project I'd be using it in is open source as well https://github.com/williamspiro/HubSpot-Developer-Extension

let me know if this is of interest to you, if not that's okay. Just thought it would be useful.

**Comment by PatMyron** [comment]
@TheWebTech Do these options work for your use-case?

https://github.com/postcss/autoprefixer#usage

`"There is also a standalone build for the browser or for a non-Node.js runtime."`

**Comment by ymatuhin** [comment]
You can take a look at the source code as an example and fetch the required packages through https://unpkg.com/ or something like this. And @PatMyron has already mentioned that and has given you a link https://raw.githubusercontent.com/ai/autoprefixer-rails/master/vendor/autoprefixer.js
So you are free to use it just pass the code and config. Good luck 👍

**Comment by TheWebTech** [comment]
Thank you, i will give it a shot
