### ISSUE TITLE
Autoprefixer generically adds prefixes to browser-specific pseudo-classes

### ISSUE THREAD

**Issue by djibe** [autoprefixer/autoprefixer.github.io#38]
Hi, how to block autoprefixer from adding -webkit prefixes to a Mozilla specific extension ?

Here are some examples to make my point :

```
.custom-range::-moz-range-thumb {
    -webkit-transition: none;
    transition: none
}
```

-webkit-transition has nothing to do here as it is a Mozilla specific selector (::-moz-range-thumb).

Another crazy output happens with keyframes and transitions, as Autoprefixer creates useless variants
```

  -webkit-transition: -webkit-box-shadow 0.1s ease-out;
  transition: -webkit-box-shadow 0.1s ease-out;
  transition: box-shadow 0.1s ease-out;
  transition: box-shadow 0.1s ease-out, -webkit-box-shadow 0.1s ease-out;
```

Instead of just

```
-webkit-transition: -webkit-box-shadow 0.1s ease-out;
      transition: box-shadow 0.1s ease-out;
```

How to fix this ? Thanks for your help. And thanks a lot for Autoprefixer !!!

**Comment by ymatuhin** [comment]
Hey, thanks for reporting it. 
This is a repo for autoprefixer web interface, if you think that autoprefixer itself doesn't work properly, please add an issue to the https://github.com/postcss/autoprefixer

**Comment by djibe** [comment]
Ooooooops ... My fault. Sorry ;)
