### ISSUE TITLE
Browsers list error

### ISSUE THREAD

**Issue by mnsrv** [autoprefixer/autoprefixer.github.io#4]
I cant filter prefixes on specific browser (like 'Safari'). Console output error:

`Uncaught BrowserslistError: Unknown browser query 'Safari'`
 autoprefixer.js:5322

may be something went wrong with browser list in database or smth...

**Comment by ymatuhin** [comment]
I'm sorry, it wasn't so clear. You must write Safari + version number. For example `Safari 8`.
