### ISSUE TITLE
Title hover is too noise

### ISSUE THREAD

**Issue by ai** [autoprefixer/autoprefixer.github.io#4]
Wheen you hover on title, it completly changes to description. This type of animation is too noise.

**Comment by ymatuhin** [comment]
What do you have in mind when you wrote "noise"? I don't understand you.

**Comment by ai** [comment]
Очень шумно. Огромный блок меняется. И меняется неожиданно.

**Comment by ymatuhin** [comment]
Исправил 7ca4d99f6460f984a4394203beeef68a963e9090
