### ISSUE TITLE
flex-wrap: nowrap does not works with chrome < 29

### ISSUE THREAD

**Issue by SuperPat45** [autoprefixer/autoprefixer.github.io#44]
I tested my site with the old chromium portable version 21 and I found that the property:
`flex-wrap: nowrap;`
who was prefixed with:
`-webkit-flex-wrap: nowrap;`
does not work with this browser, nowrap is not a valid value, however, it works fine if I add property:
`-webkit-flex-wrap: none;`

**Comment by ymatuhin** [comment]
Hey, this is just an online version of the autoprefixer itself. Such questions should be adressed to the main repo https://github.com/postcss/autoprefixer
