### ISSUE TITLE
Add a comment to generated CSS

### ISSUE THREAD

**Issue by richb-hanover** [autoprefixer/autoprefixer.github.io#47]
What a fabulous project! Thanks for making this so easy (and attractive)!

A request: Add a comment to the top of the generated CSS indicating its source. For example:

`/* CSS prefixed by autoprefixer.github.io */`

or even include version numbers:

`/* CSS prefixed by autoprefixer.github.io - Postcss: v7.0.17, autoprefixer: v9.6.1 */`

This would help weak-brained people (like me) remember where to get a refresh if I have to update the underlying CSS. Thanks again!

**Comment by ymatuhin** [comment]
@richb-hanover thanks for this great idea. It's on production now. Enjoy 👍
