### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by oguilleux** [autoprefixer/autoprefixer.github.io#55]
Hi there,

I'm having this error in my console when I create my build with autoprefixer : 

"Browserslist: caniuse-lite is outdated. Please run next command `npm update`"

I tried : 
`sudo npm i -g browserslist caniuse-lite`
and
`sudo npm i -g autoprefixer caniuse-lite`

but nothing worked, I still have the warning.

Thanks for your help

**Comment by ymatuhin** [comment]
Hey, this repo is only for online version. With that kind of question you have to go to the main repo https://github.com/postcss/autoprefixer Thanks.

**Comment by oguilleux** [comment]
Ok sure sorry.
