### ISSUE TITLE
Bump autoprefixer from v9 to v10

### ISSUE THREAD

**Issue by lukewarlow** [autoprefixer/autoprefixer.github.io#71]
It would be good to update this project to the latest autoprefixer and postcss versions to get the latest improvements in autoprefixer.

**Comment by ai** [comment]
@ymatuhin do you have problem with PostCSS 8 API?

**Comment by ymatuhin** [comment]
No i had a problem with ruby on my local machine, I'll take a closer look

**Comment by ymatuhin** [comment]
Bumped
