### ISSUE TITLE
Flexbox prefixing

### ISSUE THREAD

**Issue by hexalys** [autoprefixer/autoprefixer.github.io#9]
The 'flex' prefixing applied by autoprefixer is incorrect. If you choose the 'last 2 versions' or 'last 4 versions' it should account for UCBrowser's lack of support and include -webkit-box (or for that matter -moz-box as well for UCMini's current version, although not as important).

While the Android UCBrowser is not used much if at all in the Western or Northern hemisphere, it reaches past 40% usage in India and China for a global usage of over 8%.

It appears misguided for a dev especially  in Asia to be using autoprefixer without including -webkit-box for the last version of the UCBrowser, as well as current versions of odd balls browsers like the current Tesla QtCarBrowser not yet supporting -webkit-flex or flex.

Could this be addressed?

**Comment by ymatuhin** [comment]
Ping @ai

**Comment by ai** [comment]
@hexalys `last n versions` contains only major browsers https://github.com/ai/browserslist#major-browsers

**Comment by hexalys** [comment]
@ai Ok. That seems to amplify the issue.

Current minor browsers being treated as second class citizens is a problem... I'd suggest a need to fix, or to be more explicit about this. So that the proper expectation is made clear to devs using it.

The [mentioned notes](https://autoprefixer.github.io) says it aligns with caniuse. But if current browsers listed on caniuse with significant market share are not considered. It becomes misleading.

**Comment by ai** [comment]
@hexalys It is wrong place to talk about Browserslist and Autoprefixer. Please create a issue in Browserslist, I will think about changing the API.
